### ISSUE TITLE
ResolvePackageNotFound error when using the .yml file to setup conda environment

### ISSUE THREAD

**Issue by shaabhishek** [MLforHealth/MIMIC_Extract#13]
First of all, thanks a lot for documenting the process of working with the MIMIC-III data! I'm currently trying to setup the conda environment like it mentions on the README page but facing this error: 

```
$ conda env create --force -f ../mimic_extract_env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - hdf5==1.8.17=2
  - tk==8.5.18=0
  - pycairo==1.10.0=py27_0
  - tornado==4.5.2=py27_0
  - sqlite==3.13.0=0
  - pathlib2==2.2.1=py27_0
  - zeromq==4.1.5=0
  - libgfortran==3.0.0=1
  - pexpect==4.2.1=py27_0
  - pip==9.0.1=py27_1
  - xz==5.2.3=0
  - libxcb==1.12=1
  - pcre==8.39=1
  - freetype==2.5.5=2
  - html5lib==0.9999999=py27_0
  - jinja2==2.9.6=py27_0
  - fontconfig==2.12.1=3
  - jupyter_core==4.3.0=py27_0
  - simplegeneric==0.8.1=py27_1
  - python==2.7.13=0
  - wheel==0.29.0=py27_0
  - ipython==5.3.0=py27_0
  - icu==54.1=0
  - gst-plugins-base==1.8.0=0
  - ptyprocess==0.5.1=py27_0
  - jupyter_console==5.2.0=py27_0
  - libxml2==2.9.4=0
  - readline==6.2=2
  - jpeg==9b=0
  - scipy==0.19.1=np113py27_0
  - libiconv==1.14=0
  - jupyter_client==5.1.0=py27_0
  - zlib==1.2.8=3
  - pyparsing==2.2.0=py27_0
  - entrypoints==0.2.3=py27_0
  - widgetsnbextension==3.0.2=py27_0
  - sip==4.18=py27_0
  - markupsafe==1.0=py27_0
  - dateutil==2.4.1=py27_0
  - mistune==0.7.4=py27_0
  - libpng==1.6.30=1
  - ssl_match_hostname==3.5.0.1=py27_0
  - cairo==1.14.8=0
  - qt==5.6.2=5
  - libpq==9.5.4=0
  - pytz==2017.2=py27_0
  - pyzmq==16.0.2=py27_0
  - numexpr==2.6.2=np113py27_0
  - sqlalchemy==1.1.13=py27_0
  - dbus==1.10.20=0
  - scandir==1.5=py27_0
  - enum34==1.1.6=py27_0
  - setuptools==27.2.0=py27_0
  - decorator==4.0.11=py27_0
  - pixman==0.34.0=0
  - jupyter==1.0.0=py27_3
  - ipykernel==4.6.1=py27_0
  - ipywidgets==6.0.0=py27_0
  - backports==1.0=py27_0
  - pandocfilters==1.4.2=py27_0
  - scikit-learn==0.19.0=np113py27_0
  - python-dateutil==2.6.1=py27_0
  - glib==2.50.2=1
  - get_terminal_size==1.0.0=py27_0
  - openssl==1.0.2l=0
  - expat==2.1.0=0
  - h5py==2.7.0=np113py27_0
  - mkl==2017.0.3=0
  - notebook==5.0.0=py27_0
  - path.py==10.3.1=py27_0
  - matplotlib==2.0.2=np113py27_0
  - functools32==3.2.3.2=py27_0
  - gstreamer==1.8.0=0
  - pydotplus==2.0.2=py27_0
  - libsodium==1.0.10=0
  - pyqt==5.6.0=py27_2
  - libffi==3.2.1=1
  - bleach==1.5.0=py27_0
  - prompt_toolkit==1.0.14=py27_0
  - six==1.10.0=py27_0
  - terminado==0.6=py27_0
  - nbconvert==5.2.1=py27_0
  - psycopg2==2.7.1=py27_0
  - subprocess32==3.2.7=py27_0
  - pytables==3.4.2=np113py27_0
```

**Comment by bbardakk** [comment]
Could you please try it again after update your conda ?

**Comment by shaabhishek** [comment]
That did not work for me - but what did work was removing the versions from all packages in the yml file and anaconda figure it out on its own.

I basically modified the yml file to this: 
```
name: mimic_data_extraction
channels:
  - defaults
dependencies:
  - backports
  - backports_abc
  - bleach
  - cairo
  - configparser
  - cycler
  # - dateutil
  - dbus
  - decorator
  - entrypoints
  - enum34
  - expat
  - fontconfig
  - freetype
  - functools32
  - get_terminal_size
  - glib
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - html5lib
  - icu
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - libffi
  - libgcc-ng
  # - libgfortran
  - libgfortran-ng
  - libiconv
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libxcb
  - libxml2
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - nbconvert
  - nbformat
  - notebook
  - numexpr
  - numpy
  - openssl
  - pandas
  - pandocfilters
  - path.py
  - pathlib2
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - prompt_toolkit
  - psycopg2
  - ptyprocess
  - pycairo
  - pydotplus
  - pygments
  - pyparsing
  - pyqt
  - pytables
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - scandir
  - scikit-learn
  - scipy
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - sqlalchemy
  - sqlite
  - ssl_match_hostname
  - subprocess32
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - wcwidth
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zlib
  - pip:
    - backports.shutil-get-terminal-size
    - backports.ssl-match-hostname
    - cchardet
    - certifi
    - chardet
    - click
    - datapackage
    - et-xmlfile
    - idna
    - ijson
    - isodate
    - jdcal
    - jsonlines
    - jsonpointer
    - linear-tsv
    - openpyxl
    - requests
    - rfc3986
    - tables
    - tableschema
    - tabulator
    - unicodecsv
    - urllib3
    - xlrd
prefix: /scratch/conda_envs/mimic_data_extraction
```

**Comment by ceguimaraes** [comment]
> That did not work for me - but what did work was removing the versions from all packages in the yml file and anaconda figure it out on its own.
> 
> I basically modified the yml file to this:
> 
> ```
> name: mimic_data_extraction
> channels:
>   - defaults
> dependencies:
>   - backports
>   - backports_abc
>   - bleach
>   - cairo
>   - configparser
>   - cycler
>   # - dateutil
>   - dbus
>   - decorator
>   - entrypoints
>   - enum34
>   - expat
>   - fontconfig
>   - freetype
>   - functools32
>   - get_terminal_size
>   - glib
>   - gst-plugins-base
>   - gstreamer
>   - h5py
>   - hdf5
>   - html5lib
>   - icu
>   - ipykernel
>   - ipython
>   - ipython_genutils
>   - ipywidgets
>   - jinja2
>   - jpeg
>   - jsonschema
>   - jupyter
>   - jupyter_client
>   - jupyter_console
>   - jupyter_core
>   - libffi
>   - libgcc-ng
>   # - libgfortran
>   - libgfortran-ng
>   - libiconv
>   - libpng
>   - libpq
>   - libsodium
>   - libstdcxx-ng
>   - libxcb
>   - libxml2
>   - markupsafe
>   - matplotlib
>   - mistune
>   - mkl
>   - nbconvert
>   - nbformat
>   - notebook
>   - numexpr
>   - numpy
>   - openssl
>   - pandas
>   - pandocfilters
>   - path.py
>   - pathlib2
>   - pcre
>   - pexpect
>   - pickleshare
>   - pip
>   - pixman
>   - prompt_toolkit
>   - psycopg2
>   - ptyprocess
>   - pycairo
>   - pydotplus
>   - pygments
>   - pyparsing
>   - pyqt
>   - pytables
>   - python
>   - python-dateutil
>   - pytz
>   - pyzmq
>   - qt
>   - qtconsole
>   - readline
>   - scandir
>   - scikit-learn
>   - scipy
>   - setuptools
>   - simplegeneric
>   - singledispatch
>   - sip
>   - six
>   - sqlalchemy
>   - sqlite
>   - ssl_match_hostname
>   - subprocess32
>   - terminado
>   - testpath
>   - tk
>   - tornado
>   - tqdm
>   - traitlets
>   - wcwidth
>   - wheel
>   - widgetsnbextension
>   - xz
>   - zeromq
>   - zlib
>   - pip:
>     - backports.shutil-get-terminal-size
>     - backports.ssl-match-hostname
>     - cchardet
>     - certifi
>     - chardet
>     - click
>     - datapackage
>     - et-xmlfile
>     - idna
>     - ijson
>     - isodate
>     - jdcal
>     - jsonlines
>     - jsonpointer
>     - linear-tsv
>     - openpyxl
>     - requests
>     - rfc3986
>     - tables
>     - tableschema
>     - tabulator
>     - unicodecsv
>     - urllib3
>     - xlrd
> prefix: /scratch/conda_envs/mimic_data_extraction
> ```

Solved my issue. Thanks.

**Comment by zhangyongheng78** [comment]
Hi, did you guys met the following issue:
PackagesNotFoundError: The following packages are not available from current channels:
  - libgcc-ng
  - libstdcxx-ng
