### ISSUE TITLE
make build_curated_from_psql command fails

### ISSUE THREAD

**Issue by bbardakk** [MLforHealth/MIMIC_Extract#14]
Hi,

When I run  `make build_curated_from_psql` command, I took the error in the below. I think that I applied all steps in the README file but still, the code doesn't work. Any help is appreciated.

> pandas.io.sql.DatabaseError: Execution failed on sql '
>         select distinct i.subject_id, i.hadm_id, i.icustay_id,
>             i.gender, i.admission_age as age, a.insurance,
>             a.deathtime, i.ethnicity, i.admission_type, s.first_careunit,
>             CASE when a.deathtime between i.intime and i.outtime THEN 1 ELSE 0 END AS mort_icu,
>             CASE when a.deathtime between i.admittime and i.dischtime THEN 1 ELSE 0 END AS mort_hosp,
>             i.hospital_expire_flag,
>             i.hospstay_seq, i.los_icu,
>             i.admittime, i.dischtime,
>             i.intime, i.outtime
>           FROM icustay_detail i
>           INNER JOIN admissions a ON i.hadm_id = a.hadm_id
>           INNER JOIN icustays s ON i.icustay_id = s.icustay_id
>           WHERE s.first_careunit NOT like 'NICU'
>           and i.hadm_id is not null and i.icustay_id is not null
>           and i.hospstay_seq = 1
>           and i.icustay_seq = 1
>           and i.admission_age >= 15
>           and i.los_icu >= 0.5
>           and (i.outtime >= (i.intime + interval '12 hours'))
>           and (i.outtime <= (i.intime + interval '240 hours'))
>           ORDER BY subject_id
>           LIMIT 100
>           ;
>           ': column i.admission_age does not exist
> LINE 3:             i.gender, i.admission_age as age, a.insurance,
>                               ^
> HINT:  Perhaps you meant to reference the column "i.admission_type".
> 
> Makefile:16: recipe for target 'build_curated_from_psql' failed
> make: *** [build_curated_from_psql] Error 1

**Comment by bbardakk** [comment]
The code workes when I changed `i.admission_age` to `i.age` and `icustay` to` mimiciii.icustay`. I don't know this is correct way but at least it works.

**Comment by shaabhishek** [comment]
Only making the change `i.admission_age` to `i.age` worked for me.

**Comment by mmcdermott** [comment]
Apologies for the slow response; we've just pushed a new release, which we believe should have fixed all outstanding issues. Please re-open if you encounter any new issues.
