### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bbardakk** [MLforHealth/MIMIC_Extract#16]
I am trying to run Baselines for Mortality and LOS prediction notebook but there are missing files.
Where can I find the below files ?
> '/scratch/mmd/mimic_data/final/nogrouping_5/all_hourly_data.h5'

 and 

> '/scratch/mmd/extraction_baselines-sklearn.pkl'

**Comment by rishabhrrk** [comment]
@bbardakk where did you find extraction_baselines-sklearn.pkl?

**Comment by amirdol** [comment]
@rishabhrrk @bbardakk I also can't find it anywhere...

**Comment by TianJl1999** [comment]
@bbardakk @rishabhrrk @amirdol @mmcdermott @michaelchughes    I also can't find the .pkl file anywhere, please tell me how to get this file or where to find it, thank you so much!!!

**Comment by mmcdermott** [comment]
Thank you @TianJl1999 for re-raising this issue. I apologize for the confusion here; that file isn't released with the repository, but is instead created when you run the cells below. E.g., the line `with open(RESULTS_PATH, mode='wb') as f: pickle.dump(results, f)` saves the results that you generate in that notebook to that path. The cell reading in the file is there only to enable you to easily re-generate results or resume from partially completed runs. However, clearly our code assumes it exists at the start too, which is a mistake. 

For now, if you want to run this notebook, you should change `RESULTS_PATH` to refer to a different location on your machine (wherever you want results to be stored), comment out this line `with open(RESULTS_PATH, mode='rb') as f: results = pickle.load(f)` and then run the below cells as normal after that. Apologies for the inconvenience, and thanks for raising this to our attention!
