### ISSUE TITLE
"make build_concepts" does not work.

### ISSUE THREAD

**Issue by elmonten** [MLforHealth/MIMIC_Extract#19]
Hi! 

I'm trying to install the staging branch and I keep having troubles at the early steps. I got stuck on the [Step 4](https://github.com/MLforHealth/MIMIC_Extract/tree/staging). 

I have changed the environmental variables to:
```bash
export DBUSER=postgres
export DBNAME=mimic
export SCHEMA=mimiciii
export HOST=localhost
export DBSTRING="dbname=$DBNAME options=--search_path=$SCHEMA"
```
and it launches this error:

```bash
(mimic_extract_py36) user@computer:~/Documents/MIMIC_Extract-staging/utils$ make build_concepts
{ \
source setup_user_env.sh; \
[ -e ../../mimic-code/buildmimic/postgres/Makefile ] || git clone https://github.com/MIT-LCP/mimic-code/ ../../mimic-code/; \
}
{ \
source setup_user_env.sh; \
cd ../../mimic-code/concepts; \
psql -U  "" -h  -f ./make-concepts.sql; \
cd ../../MIMIC_Extract-staging/utils; \
}
psql: could not translate host name "-f" to address: Name or service not known
{ \
source ./setup_user_env.sh; \
psql -U  "" -h  -f ./niv-durations.sql; \
psql -U  "" -h  -f ./crystalloid-bolus.sql; \
psql -U  "" -h  -f ./colloid-bolus.sql; \
}
psql: could not translate host name "-f" to address: Name or service not known
psql: could not translate host name "-f" to address: Name or service not known
psql: could not translate host name "-f" to address: Name or service not known
Makefile:46: recipe for target 'build_extra_concepts' failed
make: *** [build_extra_concepts] Error 2
```

Does anyone have any solution? Thank you very much in advance :)

**Comment by BXL3243** [comment]
I also have the same problem, have you fixed it? Thanks so much

**Comment by BXL3243** [comment]
> Hi!
> 
> I'm trying to install the staging branch and I keep having troubles at the early steps. I got stuck on the [Step 4](https://github.com/MLforHealth/MIMIC_Extract/tree/staging).
> 
> I have changed the environmental variables to:
> 
> ```shell
> export DBUSER=postgres
> export DBNAME=mimic
> export SCHEMA=mimiciii
> export HOST=localhost
> export DBSTRING="dbname=$DBNAME options=--search_path=$SCHEMA"
> ```
> 
> and it launches this error:
> 
> ```shell
> (mimic_extract_py36) user@computer:~/Documents/MIMIC_Extract-staging/utils$ make build_concepts
> { \
> source setup_user_env.sh; \
> [ -e ../../mimic-code/buildmimic/postgres/Makefile ] || git clone https://github.com/MIT-LCP/mimic-code/ ../../mimic-code/; \
> }
> { \
> source setup_user_env.sh; \
> cd ../../mimic-code/concepts; \
> psql -U  "" -h  -f ./make-concepts.sql; \
> cd ../../MIMIC_Extract-staging/utils; \
> }
> psql: could not translate host name "-f" to address: Name or service not known
> { \
> source ./setup_user_env.sh; \
> psql -U  "" -h  -f ./niv-durations.sql; \
> psql -U  "" -h  -f ./crystalloid-bolus.sql; \
> psql -U  "" -h  -f ./colloid-bolus.sql; \
> }
> psql: could not translate host name "-f" to address: Name or service not known
> psql: could not translate host name "-f" to address: Name or service not known
> psql: could not translate host name "-f" to address: Name or service not known
> Makefile:46: recipe for target 'build_extra_concepts' failed
> make: *** [build_extra_concepts] Error 2
> ```
> 
> Does anyone have any solution? Thank you very much in advance :)

I also have the same problem, have you fixed it? Thanks so much

**Comment by elmonten** [comment]
Hello, 

No, sorry, I have not fixed it yet. I might try to install the tool again, but I have to focus on other things as of now. If you can fix it, I'd truly appreciate you share it.

**Comment by mmcdermott** [comment]
Apologies for the slow response. MIMIC modified their code-base rendering our README instructions insufficient to build concepts. We've just pushed a new release, with new instructions, which we believe should have fixed this and all outstanding issues. Please re-open if you encounter any new issues.
