### ISSUE TITLE
Number of Vital and lab feature

### ISSUE THREAD

**Issue by HuyNguyen97** [MLforHealth/MIMIC_Extract#21]
I read in the MIMIC-extract  paper that there are 93 vital and lab features. However, when i read the appendix B, i just found about 67 features. Moreover, in thi file vitals_colnames.txt generated when extracting feature, i found that there are only 91 features.

Why there are 3 different number of features like this?

**Comment by bnestor** [comment]
The 67 is for the Level2 aggregates. For example when mapping between CareVue and MetaVision, there will be 2 different measures for bilrubin, which will be aggregated in Level 2. I am not sure about the 91 vs. 93. Perharps @shirly1024 would know?
