### ISSUE TITLE
Own itemid_to_variable_map

### ISSUE THREAD

**Issue by RotemSap** [MLforHealth/MIMIC_Extract#22]
First thank you so much for this code and great baseline.
I am trying to run mimic_direct_extract.py with my own Mapping file:

[new_mimic_map.xlsx](https://github.com/MLforHealth/MIMIC_Extract/files/4663002/new_mimic_map.xlsx)

but keep getting the error:

> starting db query with 3000 subjects...
>   db query finished after 630.865 sec
> ..//mimic_direct_extract.py:265: FutureWarning: Using 'rename_axis' to alter labels is deprecated. Use '.rename' instead
>   {'LEVEL2': 'LEVEL2', 'LEVEL1': 'LEVEL1', 'ITEMID': 'itemid'}, axis=1
> Traceback (most recent call last):
>   File "..//mimic_direct_extract.py", line 887, in <module>
>     min_percent=args['min_percent']
>   File "..//mimic_direct_extract.py", line 281, in save_numerics
>     X = X.join(var_map).join(I).set_index(['label', 'LEVEL1', 'LEVEL2'], append=True)
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/frame.py", line 6815, in join
>     rsuffix=rsuffix, sort=sort)
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/frame.py", line 6830, in _join_compat
>     suffixes=(lsuffix, rsuffix), sort=sort)
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 48, in merge
>     return op.get_result()
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 546, in get_result
>     join_index, left_indexer, right_indexer = self._get_join_info()
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 744, in _get_join_info
>     sort=self.sort)
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3245, in join
>     return_indexers=return_indexers)
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3394, in _join_multi
>     return_indexers=return_indexers)
>   File "/home/rotem/anaconda3/envs/mimic_data_extraction/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3474, in _join_level
>     raise NotImplementedError('Index._join_level on non-unique index '
> NotImplementedError: Index._join_level on non-unique index is not implemented
> Makefile:16: recipe for target 'build_curated_from_psql' failed
> make: *** [build_curated_from_psql] Error 1

Can you think of something I am doing wrong with my mapping file?
Thank you again for sharing that wonderful work

**Comment by GuilhermeRamos331** [comment]
Hello! Did you solve this issue? I am having the same problem..

**Comment by RotemSap** [comment]
Yes.
The iremid column has to be unique.
I had the same row cpied twice soi had the same itemid twice.
Hope it helped
