### ISSUE TITLE
LOINC codes in item_id_to_variable_map.csv

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [MLforHealth/MIMIC_Extract#23]
It seems the [item_id_to_variable_map.csv](https://github.com/MLforHealth/MIMIC_Extract/blob/master/resources/itemid_to_variable_map.csv) file in resources directory has been opened by MS Excel and many of the LOINC codes have been converted to dates!
For example, the LOINC code for Albumin has changed from "1751-7" to "7/1/1751".
Would you please upload the corrected version?
@mmcdermott  
@shirly1024 
@mghassem 
@bnestor 
Thanks!

**Comment by mmcdermott** [comment]
Hi @Amin-Tajgardoon - sorry for the long delay in getting to your issue. We don't have a fix yet, but are tracking this. Unfortunately we're going to have to re-generate this file with proper LOINC codes. In the meantime, if you need an immediate workaround, we think you should be able to pull this data out via SQL from `mimiciii.d_labitems` in the meantime. We should have an updated file posted soon, but wanted to raise that workaround in case your need was urgent.
