### ISSUE TITLE
There maybe bugs in simple_imputer() when computing "hours of absence"

### ISSUE THREAD

**Issue by xlbryantx** [MLforHealth/MIMIC_Extract#27]
In simpler_imputer(), I think " hours_of_absence = is_absent.cumsum()" should be " hours_of_absence = is_absent.groupby().cumsum()"

**Comment by mmcdermott** [comment]
Thanks for raising this @xlbryantx  -- what makes you think this groupby is needed? Also, can you confirm what commit of the code you're running, on what release of MIMIC-III / commit of mimic-code?

**Comment by mmcdermott** [comment]
@xlbryantx I'm going to close this for now, as I've not heard from you verifying the issue, but feel free to re-open with more detail and I'll look into it.

**Comment by JHLiu7** [comment]
Hi @mmcdermott thanks for the great work in maintaining the project. But I also found this might be an issue with the imputer. Without `groupby`, `time_since_measured` may start counting from its previous stay in the dataframe, and I could find something like this 
<img width="650" alt="screenshot" src="https://user-images.githubusercontent.com/59333371/142557809-76c6c084-9835-49e9-9db7-0a708543716f.png">
though I'm not sure how this may impact models like gru-d.

**Comment by JHLiu7** [comment]
Actually just submitted a pull request, hope it helps
