### ISSUE TITLE
MIMIC-Extract for MIMIC-IV

### ISSUE THREAD

**Issue by bbardakk** [MLforHealth/MIMIC_Extract#30]
Hi, 

Do you have a plan to modify MIMIC-Extract for MIMIC-IV in a short time or do you think that MIMIC-Extract can works on MIMIC-IV with minimal modifications?

Thanks in advance.

**Comment by mmcdermott** [comment]
We do plan to modify it to work with MIMIC-IV, but don't have a definite timeline yet. We'll post any updates on this issue as the situation evolves!

**Comment by phaniparsa** [comment]
@mmcdermott: Any updates on the timeline to support MIMIC-IV?

**Comment by hildeweerts** [comment]
As MIMIC-III is phased out, are there any updates on the timeline to support MIMIC-IV?

**Comment by bnestor** [comment]
Hi, MIMIC-IV is undergoing a demo for OMOP formatting (https://physionet.org/content/mimic-iv-demo-omop/0.9/). I think we should hold off until OMOP is available so that we don't need to build an extraction pipeline for each hospital/version that comes along. But open to discussion.

**Comment by bnestor** [comment]
Hi, I just pushed a MIMIC-IV extraction script to mimiciv_extract branch. It is not perfect yet. A lot of the variable limits etc, need to be addressed. That being said, it is a good start as an additional benchmark now that we have mimiciii_extract, eicu_extract, and mimiciv_extract.  Existing alternatives would be pyhealth for OMOP or mimiciv: https://pyhealth.readthedocs.io/en/latest/api/datasets/pyhealth.datasets.OMOPDataset.html  Gen HPF: https://github.com/hoon9405/GenHPF ESGPT: https://github.com/mmcdermott/EventStreamGPT amongst others FHIR: https://github.com/google/fhir/tree/master for MIMICIV-on-FHIR https://physionet.org/content/mimic-iv-fhir/1.0/
