### ISSUE TITLE
Itemid_to_variable line 13252 has 28 values

### ISSUE THREAD

**Issue by andinjo** [MLforHealth/MIMIC_Extract#35]
The [itemid_to_variable.csv](https://github.com/MLforHealth/MIMIC_Extract/blob/master/resources/itemid_to_variable_map.csv) line 13252 seems to have gotten 28 values, while the other lines have 18. Looks like it has gotten half of another row in it.

**Comment by bendikjohansen** [comment]
After further examination, it appears that a large chunk of the text has been duplicated (the final 606 lines in the document). This can easily be verified by searching for `,ne,` in the document and selecting everything after `ne,`. This should have two matches in the document.

**Comment by bnestor** [comment]
Fixed in #36
