### ISSUE TITLE
How to extract multiple ICU stays from each patient?

### ISSUE THREAD

**Issue by ducnx** [MLforHealth/MIMIC_Extract#40]
As the question states, can you please give instructions on how to extract multiple ICU stays from each patient, e.g which functions do we have to modify?
Thank you.

**Comment by ducnx** [comment]
Further details for the first comment: I know that MIMIC_Extract defaults to extract first ICU admissions. However, some researches use multiple ICU stays for evaluation and I want to compare fairly with them. That's why I raise the issue.
I know that I have to modify the `mimic_direct_extract.py` file, but I'm not sure where to change.

**Comment by mmcdermott** [comment]
Unfortunately, this isn't something we natively support and I don't have the cycles immediately to give a full walk through, but I suspect changing the population extraction query to remove that filter would work on its own, actually. See here for that filter: https://github.com/MLforHealth/MIMIC_Extract/blob/master/SQL_Queries/statics.sql#L53

Hope that helps, and as with #41 please feel free to file another issue as a feature request if this is something you'd like us to officially support, and we'll get to it when we can!
