### ISSUE TITLE
How to remove grouping measurements hourly

### ISSUE THREAD

**Issue by ducnx** [MLforHealth/MIMIC_Extract#41]
Some other baselines do not group the measurements hourly as yours, if I want to do that using your pipeline, how should I modify the code (I guess it's the file `mimic_direct_extract.py`), i.e. which functions do I have to look at?

**Comment by mmcdermott** [comment]
Yes, right now we don't support this, but you could enable this by modifying `mimic_direct_extract.py`. I'm not sure exactly where you'd need to modify off-hand. It is likely that systemic modifications are required, as you will need to do more than just modify the various `group_by` calls, but also ensure that other aspects of the pipeline play well with a differently structured index. The simplest option that might work would be to simply change the `'hours_in'` index to a `seconds_in` or whatever granularity you desire and keep everything else identical, but I can't guarantee that would work.

Unfortunately we don't have bandwidth immediately to give more detailed instructions or make this change, but if you'd like a mode of this pipeline that allows for extracting at full granularity, feel free to open an issue requesting that feature and we'll get to it when we can. Hopefully that helps!
