### ISSUE TITLE
Authorization issue mimic_extract Google Cloud Bucket: Forbidden Error 403

### ISSUE THREAD

**Issue by hildeweerts** [MLforHealth/MIMIC_Extract#49]
I am having trouble downloading the pre-processed mimic_extract data from the google cloud bucket. I still have access to the bucket, but when I try to download it, I am redirected to a page that says "Forbidden Error 403". 

<img width="204" alt="Screen Shot 2021-03-19 at 15 57 15" src="https://user-images.githubusercontent.com/24417440/111800134-f4b25a80-88cb-11eb-8b1a-f7d0ee8f0673.png">

Up until recently I had no problems downloading the data set.

**Comment by mmcdermott** [comment]
Hi @hildeweerts -- can you check now? I may have resolved the issue.

**Comment by hildeweerts** [comment]
Hi @mmcdermott! Thank you for the quick response. It is working now!
