### ISSUE TITLE
Why feature dimension largely reduced i.e. 6-19 features depending on the value of missingness.  for instance: with 100% missing values will have 104 or so columns, but if we set to 1 or 50% missing values it will be reduced up to 6 features where number of patient is constant. 

### ISSUE THREAD

**Issue by pvsnp9** [MLforHealth/MIMIC_Extract#53]

**Comment by bnestor** [comment]
The data is asynchronous. Not every patient requires every measurement at every time-point. For example cardiac patients wouldn't require constant kidney screening labs (if at all). This appears as sparsity/missingness.
